baseurl = "https://cyberknight777.dev"
languageCode = "en-us"
title = "Knight's Blog"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "A simple theme for Hugo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
